version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Toronto
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      go-routine-updates:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]
      go-security-updates:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: America/Toronto
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      action-routine-updates:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]
      action-security-updates:
        applies-to: security-updates
        patterns: ["*"]
